.\" SPDX-FileCopyrightText: 2025 Luca Kredel <luca.kredel@web.de>
.\" SPDX-License-Identifier: GFDL-1.3-or-later

.TH YOCTOFETCH 1
.SH NAME
yoctofetch - system fetch tool
.SH SYNOPSIS
.B yoctofetch
[OPTIONS]
.SH DESCRIPTION
Fast(est) system fetch tool for Linux with a low footprint.

Similar to neofetch etc. Only smaller, faster and with less features.
.SH OPTIONS
.TP
\fB-H, --no-user-at-host\fP
Do not display user@host.
.TP
\fB-O, --no-os\fP
Do not display OS.
.TP
\fB-K, --no-kernel\fP
Do not display kernel name and version.
.TP
\fB-U, --no-uptime\fP
Do not display uptime.
.TP
\fB-S, --no-shell\fP
Do not display shell.
.TP
\fB-D, --no-desktop\fP
Do not display desktop.
.TP
\fB-T, --no-terminal\fP
Do not display terminal.
.TP
\fB-M, --no-memory\fP
Do not display memory.
.TP
\fB-P, --no-swap\fP
Do not display swap.
.TP

\fB-V, --version\fP
Show version and exit.
.TP
\fB-h, --help\fP
Show this help and exit.
.TP

\fB--bottom-padding\fP
Add three lines of padding at the bottom.
.TP

\fB--guix-logo\fP
Show guix logo.
.TP
\fB--arch-logo\fP
Show arch logo.
.SH AUTHOR
Written by Luca Kredel
.SH BUGS
None, of course.
.SH REPORTING BUGS
https://codeberg.org/Phosphenius/yoctofetch/issues
.SH COPYRIGHT
Copyright (C) 2025 Luca Kredel.
License GPLv3: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl-3.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
