# Force a specific logo. Valid values are OS identifiers, like "arch", "debian".
#logo="arch"
show_os="1"
show_host="1"
show_kernel="1"
show_uptime="1"
show_shell="1"
show_desktop="1"
show_terminal="1"
show_memory="1"
show_swap="1"
